{
  "url": "https://youtu.be/c_vCrQxeSgg?si=yF-LFE7CKgPlpK0g",
  "source": "youtube",
  "title": "27 November 2023",
  "author": "",
  "thumbnail": "thumbnail link ",
  "duration": 144,
  "medias": [
    {
      "formatId": 18,
      "label": "mp4 (360p)",
      "type": "video",
      "ext": "mp4",
      "quality": "mp4 (360p)",
      "width": 640,
      "height": 352,
      "url": " download link",
      "bitrate": 688014,
      "fps": 30,
      "audioQuality": "AUDIO_QUALITY_LOW",
      "audioSampleRate": "44100",
      "mimeType": "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\"",
      "duration": 2,
      "is_audio": true,
      "extension": "mp4"
    },
    {
      "formatId": 134,
      "label": "mp4 (360p)",
      "type": "video",
      "ext": "mp4",
      "quality": "mp4 (360p)",
      "width": 640,
      "height": 352,
      "url": "download link 360p",
      "bitrate": 624108,
      "fps": 30,
      "audioQuality": null,
      "audioSampleRate": null,
      "mimeType": "video/mp4; codecs=\"avc1.4d401e\"",
      "duration": 2,
      "extension": "mp4"
    },
    {
      "formatId": 243,
      "label": "webm (360p)",
      "type": "video",
      "ext": "webm",
      "quality": "webm (360p)",
      "width": 640,
      "height": 352,
      "url": " download link 360p",
      "bitrate": 336721,
      "fps": 30,
      "audioQuality": null,
      "audioSampleRate": null,
      "mimeType": "video/webm; codecs=\"vp9\"",
      "duration": 2,
      "extension": "webm"
    },
    {
      "formatId": 160,
      "label": "mp4 (144p)",
      "type": "video",
      "ext": "mp4",
      "quality": "mp4 (144p)",
      "width": 256,
      "height": 140,
      "url": " download link 144p",
      "bitrate": 135831,
      "fps": 30,
      "audioQuality": null,
      "audioSampleRate": null,
      "mimeType": "video/mp4; codecs=\"avc1.4d400c\"",
      "duration": 2,
      "extension": "mp4"
    },
    {
      "formatId": 140,
      "label": "m4a (130kb/s)",
      "type": "audio",
      "ext": "m4a",
      "width": null,
      "height": null,
      "url": " download link m4a",
      "bitrate": 130459,
      "fps": null,
      "audioQuality": "AUDIO_QUALITY_MEDIUM",
      "audioSampleRate": "44100",
      "mimeType": "audio/mp4; codecs=\"mp4a.40.2\"",
      "duration": 2,
      "quality": "m4a (130kb/s)",
      "extension": "m4a"
    },
    {
      "formatId": 251,
      "label": "opus (138kb/s)",
      "type": "audio",
      "ext": "opus",
      "width": null,
      "height": null,
      "url": " download link audio",
      "bitrate": 138444,
      "fps": null,
      "audioQuality": "AUDIO_QUALITY_MEDIUM",
      "audioSampleRate": "48000",
      "mimeType": "audio/webm; codecs=\"opus\"",
      "duration": 2,
      "quality": "opus (138kb/s)",
      "extension": "opus"
    }
  ],
  "type": "multiple",
  "error": false,
  "time_end": 820
}
